import Head from 'next/head';
import Login from '../components/Login';
import Header from '../components/Header';
import { getSession } from 'next-auth/client';

export default function Home({ session }) {
  if(!session) return  <Login />;
  return (
    <div className="">
      <Head>
        <title>Facebook Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      {/* Header */}
      <Header />
      <main>
        {/* SIdebar */}
        
        {/* Feed */}

        {/* Widgets */}
      </main>

    </div>
     
  )
}

/* This function to get data with server side rendering */

export async function getServerSideProps(context) {
  // Get the user
  const session = await getSession(context);

  return {
    props: {
      session
    }
  }

}