import Head from 'next/head'
import Header from '../components/Header'

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Facebook Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      {/* Header */}
      <Header />
      <main>
        {/* SIdebar */}
        
        {/* Feed */}

        {/* Widgets */}
      </main>

    </div>
     
  )
}
